version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "61234:61234"
    environment:
      - REDIS_URL=redis://redis:6379
      - APIBARA_API_KEY=${APIBARA_API_KEY}
      - RUST_BACKTRACE=1  # Added for better error tracking
      - STARTING_BLOCK=${STARTING_BLOCK}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - P2P_LISTEN_ADDR=/ip4/0.0.0.0/tcp/61234
      - P2P_BOOTSTRAP_PEERS=${P2P_BOOTSTRAP_PEERS:-}
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  redis_data: